name: Release package
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  package:
    uses: landoria-gaming/LandoriaModActions/.github/workflows/release.yml@v4.5
    with:
      project-file: Landoria.SealedTombstone.csproj
      mod-name: Landoria.SealedTombstone
    secrets:
      references-token: ${{ secrets.MOD_REFERENCES_TOKEN }}
